- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install curl and ca-certificates
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present

- name: Create directory for NodeSource GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download NodeSource GPG key
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /tmp/nodesource.gpg.key

- name: Add NodeSource GPG key
  shell: gpg --dearmor < /tmp/nodesource.gpg.key > /etc/apt/keyrings/nodesource.gpg
  args:
    creates: /etc/apt/keyrings/nodesource.gpg

- name: Set proper permissions on GPG key
  file:
    path: /etc/apt/keyrings/nodesource.gpg
    mode: "0644"

- name: Add NodeSource repository
  shell: echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Update package cache after adding NodeSource repository
  apt:
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Verify Node.js installation
  command: node --version
  register: node_version
  changed_when: false

- name: Display Node.js version
  debug:
    msg: "Node.js version installed: {{ node_version.stdout }}"
